### PR TITLE
Added a question in Linux about using '--author'.

### PR DESCRIPTION
**Pull request by djkotowski**
We found on some production projects that during pairing, engineers were committing code using the same author, making it difficult to determine what code was written by which engineer.  We included this change to correct that.

### CODE REVIEW

**Comment by jmmastey** [comment]
Can you add some context to the question so that they understand why they're doing this? I think it's a good change overall, but may not be evident to folks once they're in the wild.

**Comment by djkotowski** [comment]
@jmmastey: How does this look?

**Comment by jmmastey** [comment]
Yarp. I suspect we'll see some non-enovans who get stuck on that based on not having a pairing partner, but I'll wait til I see it to try to address it.

**Comment by jmmastey** [comment]
Thanks for the change :)

**Comment by djkotowski** [comment]
Thank you for merging it.

**Pull request merged**
