### PR TITLE
Remove "look back and fix" instructions in early Ruby exercises.

### PR DESCRIPTION
**Pull request by djkotowski**
As discussed via email.

### CODE REVIEW

**Comment by jmmastey** [comment]
Does it make sense to add a note to Dinodex to make sure to conform to all previous exercises? Or do you think this is sufficient?

**Comment by djkotowski** [comment]
There was already [a note](https://github.com/jmmastey/level_up/blob/master/app/views/categories/_ruby.html.haml#L90) there.

**Comment by jmmastey** [comment]
Derp. Fair.

**Comment by jmmastey** [comment]
Deployed, thx :)

**Pull request merged**
